#!/bin/bash
# Bash script to display information about subdomains

get_record_type() {
    dig +short -t "$1" "$2" | awk 'NR==1 { print $1 }'
}

get_destination() {
    dig +short "$1" | awk 'NR==1 { print $1 }'
}

audit_subdomain() {
    local subdomain="$1"
    local domain="$2"
    
    record_type=$(get_record_type A "${subdomain}.${domain}")
    destination=$(get_destination "${subdomain}.${domain}")

    if [ -n "$record_type" ] && [ -n "$destination" ]; then
        echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
    fi
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    audit_subdomain "$sub" "$domain"
done

